export * from './base.seeder';
export * from './role.seeder';
export * from './faculty.seeder';
export * from './study-program.seeder';
export * from './report-category.seeder';
export * from './admin-user.seeder';
export * from './petugas-user.seeder';
export * from './dosen-user.seeder';
export * from './mahasiswa-user.seeder';
